name: "githubapp"

on:
  push:
  pull_request:
     branches:
      - main
  workflow_dispatch:
   

jobs:
  call_another_workflow:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     -  name: Trigger webhook workflow
        uses: SiyaaJhawar/learning-/blob/main/.github/workflows/webhook.yml@main
        with :
          event-type: trigger-webhook
     
      
   
    
    
