name: "githubapp"

on:
  push:
  pull_request:
    tags:
      - '**'
  workflow_dispatch:
   

jobs:
  call_another_workflow:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Trigger webhook workflow
     - uses: SiyaaJhawar/learning-/actions/workflows/webhook.yml@main
     
     
       with:
       
      
        event-type: trigger-webhook
        

   
    
    
