name: "githubapp"

on:
  push:
  pull_request:
    tags:
      - '**'
  workflow_dispatch:
   

jobs:
  call_another_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook workflow
      - uses: actions/checkout@v3
     
        with:
       
          repository: SiyaaJhawar/learning-/actions/workflows/webhook.yml@main
          event-type: trigger-webhook
        

   
    
    
