name: "githubapp"
on:
  push:
  pull_request:
    tags:
      - '**'
  workflow_dispatch:
 



   


jobs:
   called_workflow:
    uses: https://github.com/SiyaaJhawar/learning-/blob/main/.github/workflows/webhook.yml@main
        

   
    
    
