name: CI 

on:
  push:
    branches: [main] 
  workflow_dispatch: 

jobs:
 
  build:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -  uses: ./.github/actions/app.yml
     
     
      - name: Trigger workflow
        uses: SiyaaJhawar/learning-@main

   
    
    
