name: "githubapp"
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
 



   


jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        -name: "Hit a webhook"
        -uses: https://github.com/SiyaaJhawar/learning-@main
        

   
    
    
