name: "githubapp"
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
 



   


jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

   
    - run : npm install jsonwebtoken
    - run : npm install axios
    - run : |
       curl -i -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ghs_EsMV9jYghOYAaSZ0pC3QJbMMlD7UQI0U5geG" -H "X-GitHub-Api-Version: 2022-11-28"   http://api.github.com/repos/SiyaaJhawar/demo/issues
  #  - run : gem install jwt 

  #  - run : node  node.js
  #  -  run : node readfromapp.js
   # - run : node appinstallation.js
  #  - run : node issue.js
    - run : node issue2.js
    
   
